var content = document.getElementById("content")

document.body.addEventListener("click", (e) => {

    if(e.target.id == "uk") {
        content.innerHTML = "<b>display: flex;</b> - Ustawia elementy potomne w kontenerze w układzie blokowym, który można elastycznie kontrolować za pomocą właściwości flexbox.<br><br><b>position: absolute;</b> - Umożliwia określenie położenia elementu względem jego najbliższego kontenera pozycjonującego lub całej strony.<br><br><b>float: left;</b> - Pozwala na wyrównanie elementu do lewej strony kontenera, a inne elementy będą się owijać wokół niego.<br><br><b>margin: 0 auto;</b> - Automatycznie wyśrodkowuje element w poziomie w jego rodzicu.<br><br><b>width: 100%;</b> - Ustala szerokość elementu na 100% szerokości rodzica, co sprawia, że element zajmuje całą dostępną przestrzeń poziomą.<br><br><b>height: 100vh;</b> - Ustala wysokość elementu na 100% wysokości okna przeglądarki (viewport).<br><br><b>overflow: hidden;</b> - Ukrywa treść, która wychodzi poza granice elementu.<br><br><b>text-align: center;</b> - Wyśrodkowuje tekst wewnątrz elementu poziomo.<br><br><b>padding: 10px;</b> - Dodaje wewnętrzne marginesy do elementu, oddzielając zawartość od jego granic.<br><br><b>box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.2);</b> - Dodaje cień do elementu, co nadaje mu efekt wypukłości.<br><br><b>justify-content: space-between;</b> - Rozdziela elementy wzdłuż osi poziomej w kontenerze, tak aby zajmowały całą dostępną przestrzeń, ale równocześnie były równomiernie rozłożone z odstępem między nimi.<br><br><b>align-items: center;</b> - Wyśrodkowuje elementy wzdłuż osi pionowej w kontenerze.<br><br><b>position: fixed;</b> - Ustawia element w stałej pozycji względem okna przeglądarki, niezależnie od przewijania strony."
    } else if(e.target.id == "licz") {
        content.innerHTML = "<b>px</b> - piksele, najczęściej używane do określania rozmiaru elementów lub odstępów.<br><br><b>%</b> - procenty, stosowane do określania proporcji w odniesieniu do rozmiarów rodzica. <br><br><b>em</b> - wielkość czcionki, w której 1 em odpowiada bieżącej wielkości czcionki. <br><br><b>rem</b> - wielkość czcionki, w której 1 rem odpowiada wielkości czcionki zdefiniowanej na poziomie korzenia. <br><br><b>vh</b> - viewport height, oznacza procent wysokości okna przeglądarki. <br><br><b>vw</b> - viewport width, oznacza procent szerokości okna przeglądarki. <br><br><b>fr</b> -  jednostka elastyczna używana w gridzie, gdzie fr oznacza frakcję dostępnego miejsca. <br><br><b>s</b> - sekundy, używane do określania czasu trwania animacji lub przejścia. <br><br><b>ms</b> - milisekundy, używane do określania czasu trwania animacji lub przejścia w jednostkach milisekund. <br><br><b>deg</b> - stopnie, stosowane do określania kątów w transformacjach 2D lub 3D. <br><br>"
    } else if(e.target.id == "tlo") {
        content.innerHTML = "<b>background-color: #ffffff;</b> - Ustawia kolor tła strony na biały. Można zmienić wartość na dowolny inny kolor w formacie szesnastkowym lub nazwie koloru.<br><br><b>background-image: url(nazwazdjecia);</b> - Ustawia obrazek jako tło strony. <br><br><b>background-repeat: no-repeat;</b> - Określa, czy obrazek tła ma być powtarzany w pionie i poziomie.  <br><br><b>background-position: center;</b> - Ustawia pozycję obrazka tła na środku strony. Można również użyć innych wartości, takich jak top, bottom, left, right, aby dopasować pozycję.<br><br><b>background-size: cover;</b> - Dopasowuje rozmiar obrazka tła tak, aby wypełnił całe tło strony, bez deformacji. Można również użyć wartości contain, aby zmieścić cały obrazek wewnątrz tła.<br><br><b>background-attachment: fixed;</b> - Ustawia tło jako stałe, które nie przewija się wraz z zawartością strony. Można również użyć wartości scroll, aby tło przewijało się razem z zawartością. <br><br><b>background-blur: 5px;</b> -  Dodaje efekt rozmycia do tła strony. Wartość 5px wskazuje stopień rozmycia, który można dostosować według preferencji.<br><br><b>background-gradient: linear-gradient(to right, #ff0000, #0000ff);</b> - Tworzy gradient tła, który płynnie przechodzi od jednego koloru do drugiego.<br><br><b>background-opacity: 0.7;</b> - Ustawia przezroczystość tła, gdzie wartość 0.7 oznacza 70% przezroczystości. Ta właściwość jest często używana wraz z kolorami lub obrazkami tła."
    } else if(e.target.id == "czci") {
        content.innerHTML = "<b>font-family: Arial, sans-serif;</b> - Ustawia rodzinę czcionek dla tekstu na stronie.<br><br><b>font-size: 16px;</b> - Ustala rozmiar czcionki dla tekstu na stronie.<br><br><b>font-weight: bold;</b> - Określa wytłuszczenie tekstu.<br><br><b>font-style: italic;</b> - Nadaje tekstowi pochylenie.<br><br><b>text-decoration: underline;</b> - Dodaje podkreślenie do tekstu.<br><br><b>text-align: center;</b> - Wyśrodkowuje tekst wewnątrz elementu.<br><br><b>line-height: 1.5;</b> - Określa wysokość linii tekstu. Wartość 1.5 oznacza, że wysokość linii jest 1,5 raza większa od rozmiaru czcionki."
    } else if(e.target.id == "kol") {
        content.innerHTML = "<b>Wartość szesnastkowa</b> - Kolory można określić za pomocą kodów szesnastkowych, takich jak #ff0000 dla czerwonego koloru lub #00ff00 dla zielonego koloru. Kod szesnastkowy składa się z sześciu znaków, gdzie pierwsze dwa oznaczają wartość czerwieni, kolejne dwa - wartość zieleni, a ostatnie dwa - wartość niebieskiego.<br><br><b>Wartość RGB</b> - Kolor można również zdefiniować za pomocą wartości składowych RGB, takich jak rgb(255, 0, 0) dla czerwonego koloru. Pierwsza liczba oznacza wartość czerwieni (od 0 do 255), druga - wartość zieleni, a trzecia - wartość niebieskiego. <br><br><b>Wartość RGBA</b> - Ta notacja jest podobna do RGB, ale dodaje czwartą wartość - wartość przezroczystości (alpha). Na przykład rgba(255, 0, 0, 0.5) określa półprzezroczysty czerwony kolor.<br><br><b>Nazwa koloru</b> - Istnieje również możliwość używania nazw kolorów, takich jak red, green, blue. CSS ma zdefiniowaną listę nazw kolorów, które można używać bezpośrednio. "
    } else if(e.target.id == "anim") {
        content.innerHTML = "<b>@keyframes</b> - To at-rule w CSS, który definiuje zestaw instrukcji dla animacji. Może być używany do zdefiniowania różnych kroków animacji w czasie.<br><br><b>animation</b> - Ta właściwość CSS łączy animację z elementem i kontroluje różne aspekty animacji, takie jak czas trwania, opóźnienie, powtarzanie, sposób zapełniania i wiele innych.<br><br><b>animation-delay</b> - Ta właściwość CSS określa opóźnienie przed rozpoczęciem animacji.<br><br><b>animation-timing-function</b> - Ta właściwość CSS kontroluje sposób, w jaki animacja zmienia się w czasie.<br><br><b>animation-fill-mode</b> - Ta właściwość CSS określa, jak animacja wpływa na element przed i po jej zastosowaniu.<br><br><b>animation-name</b> - Ta właściwość CSS określa nazwę animacji zdefiniowanej za pomocą @keyframes np.<br><b>-->animation-name: move;</b><br><br><b>animation-duration</b> - Ta właściwość CSS określa czas trwania animacji np.<br><b> -->  animation: move 2s ease-in-out infinite;</b><br><br><b>animation-iteration-count</b> - Ta właściwość CSS określa liczbę powtórzeń animacji np.<br><b>-->animation: move 2s ease-in-out 3;</b><br><br><b>animation-direction</b> - Ta właściwość CSS kontroluje kierunek animacji.<br><br><b>animation-play-state</b> - Ta właściwość CSS kontroluje stan odtwarzania animacji."
    }
})